@baseUrl = http://localhost:5239

### Listar todas as sessões
GET {{baseUrl}}/api/sessoes-estudo
Accept: application/json


### Criar sessão 1 - C#
POST {{baseUrl}}/api/sessoes-estudo
Content-Type: application/json

{
  "materia": "C#",
  "topico": "FromQuery e filtros",
  "minutosEstudados": 60,
  "dificuldade": 4
}


### Criar sessão 2 - C#
POST {{baseUrl}}/api/sessoes-estudo
Content-Type: application/json

{
  "materia": "C#",
  "topico": "ActionResult e respostas HTTP",
  "minutosEstudados": 45,
  "dificuldade": 3
}


### Criar sessão 3 - Salesforce
POST {{baseUrl}}/api/sessoes-estudo
Content-Type: application/json

{
  "materia": "Salesforce",
  "topico": "Flows",
  "minutosEstudados": 50,
  "dificuldade": 4
}


### Buscar por matéria existente - C#
GET {{baseUrl}}/api/sessoes-estudo/buscar?materia=C%23
Accept: application/json


### Buscar por matéria existente usando minúscula
GET {{baseUrl}}/api/sessoes-estudo/buscar?materia=c%23
Accept: application/json


### Buscar por matéria existente - Salesforce
GET {{baseUrl}}/api/sessoes-estudo/buscar?materia=Salesforce
Accept: application/json


### Buscar por matéria inexistente
GET {{baseUrl}}/api/sessoes-estudo/buscar?materia=AWS
Accept: application/json