// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyTracker.Infrastructure.Data;

#nullable disable

namespace StudyTracker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StudyTrackerDbContext))]
    partial class StudyTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("StudyTracker.Core.Models.SessaoEstudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSessao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dificuldade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinutosEstudados")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessoesEstudo");
                });
#pragma warning restore 612, 618
        }
    }
}
